server:
  port: ${PORT:8080}
  compression:
    enabled: true
    mime-types: application/json
  http2:
    enabled: true

spring:
  application:
    name: desencurta
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false

logging:
  level:
    "[com.urlexpander]": DEBUG
    root: INFO
  pattern:
    console: "%d{HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
